# -*- mode: ruby -*-
# vi: set ft=ruby :
# author: pepe vila
# date: 2015/11/18

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "installdeps.sh"
  config.vm.provision "shell", path: "install.sh", privileged: false
end
